# Generated by Django 5.0.2 on 2024-03-05 12:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprawy', '0003_alter_sprawa_data_zakonczenia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sprawa',
            name='dane_posiadane',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.CreateModel(
            name='Notatka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_utworzenia', models.DateTimeField(default=django.utils.timezone.now)),
                ('widoczna_dla_klienta', models.BooleanField(default=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sprawa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprawy.sprawa')),
            ],
        ),
    ]
