# Generated by Django 5.0.2 on 2024-03-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprawy', '0004_sprawa_dane_posiadane_notatka'),
    ]

    operations = [
        migrations.AddField(
            model_name='notatka',
            name='tresc',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
