# Generated by Django 5.0.2 on 2024-03-07 19:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprawy', '0005_notatka_tresc'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprawa',
            name='brudnopis',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Brudnopis'),
        ),
        migrations.AlterField(
            model_name='sprawa',
            name='data_rozpoczecia',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data rozpoczęcia'),
        ),
        migrations.AlterField(
            model_name='sprawa',
            name='data_zakonczenia',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data zakończenia'),
        ),
        migrations.AlterField(
            model_name='sprawa',
            name='zakres_czynnosci',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Zakres czynności'),
        ),
        migrations.AlterField(
            model_name='sprawa',
            name='zamknieta',
            field=models.BooleanField(default=False, verbose_name='Zamknięta'),
        ),
        migrations.AlterField(
            model_name='sprawa',
            name='zgloszona_do_kpp',
            field=models.BooleanField(default=False, verbose_name='Zgłoszona do KPP'),
        ),
    ]
